### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by gfldex** [LaurentRosenfeld/thinkperl6#1]
! LaTeX Error: File `functional.tex' not found.
! LaTeX Error: File `conclusion.tex' not found.
! LaTeX Error: File `appendix_solutions.tex' not found.

**Comment by LaurentRosenfeld** [comment]
This GitHub repository is not complete yet. Some files (although already written) have not been uploaded yet (but should be soon). Other files already there need some updates.

**Comment by LaurentRosenfeld** [comment]
The three missing LaTeX files have now been uploaded in the repository. It should now be possible to proceed with a full build. But a number of files are still under review and/or proofreading and will be modified.

**Comment by LaurentRosenfeld** [comment]
The build now works correctly. The issue can be closed.
