### ISSUE TITLE
Object instantiation 

### ISSUE THREAD

**Issue by uzluisf** [LaurentRosenfeld/thinkperl6#11]
On **Subsection 12.7.1 The Pixel Class**, right after the sentence "Using the new Pixel class is straight forward:", you begin invoking methods on the Pixel object `$pix` which hasn't been defined yet. Is it up to the reader to instantiate and initialize it?

**Comment by LaurentRosenfeld** [comment]
Yes, you're right, I could have inserted the code to instantiate the object. Although, at this point in the chapter, I would assume it should be fairly obvious. I'll add a sentence saying something like "Assuming you've instantiated a $pix object..." or perhaps add code to show instantiation. Thanks.

**Comment by LaurentRosenfeld** [comment]
OK, I decided to add some code to instantiate $pix, a Pixel object.

**Comment by uzluisf** [comment]
You're right! I just wanted to make sure something wasn't missing.
