### ISSUE TITLE
Possible fix to solution (Exercise 9.12)

### ISSUE THREAD

**Issue by uzluisf** [LaurentRosenfeld/thinkperl6#16]
https://github.com/LaurentRosenfeld/thinkperl6/blob/56301edb538ee294b5cdabf5104b3030d17b40f6/book/appendix_solutions.tex#L3855-L3862

The function throws  a "Too few positionals passed; expected 2 arguments but got 1" error
when the for loop iterates over an odd-numbered word.

Possible fixes:

```
     for $word.comb -> $even, $odd='' { 
         push @evens, $even; 
         push @odds, $odd; 
    } 
```
```
     for $word.comb -> $even, $odd? { 
         push @evens, $even with $even; 
         push @odds, $odd with $odd; 
    } 
```

**Comment by uzluisf** [comment]
Few other suggestions were provided [here](http://colabti.org/irclogger/irclogger_log/perl6?date=2018-07-06#l729).

**Comment by LaurentRosenfeld** [comment]
Thank you, Luis. I used the first fix you suggested, as the second one would require additional explanations on the syntax.
