### ISSUE TITLE
Is this a free eBook?

### ISSUE THREAD

**Issue by zoffixznet** [LaurentRosenfeld/thinkperl6#2]
Hey,

I saw this repo referenced, along with the `cd book && pdflatex thinkperl6.tex` command to build the "free" eBook, but is that the intent of this repo? To provide a free version of the ebook?

The readme doesn't mention anything, so if it is meant to be the free version, it would be helpful to include that build command, along with a proper LICENSE stating the distribution limitations, if any.

**Comment by LaurentRosenfeld** [comment]
Hi,

the book front matter (in the _thinkperl6.tex_ LaTeX source file) has the following information:

_Permission is granted to copy, distribute, and/or modify this document under the terms of the
Creative Commons Attribution-NonCommercial 3.0 Unported License, which is available at http:
//creativecommons.org/licenses/by-nc/3.0/._

So yes, the intent is to make the book available free of charge in PDF format (or any other e-format the user might want to build from the LaTeX sources), as a service to the community. Anyone may also reuse the book's content provided this use complies with terms and conditions of the Creative Commons License mentioned above.

The book is also available free of charge in PDF format at the following Web address: http://greenteapress.com/wp/think-perl-6/.

I am waiting for O'Reilly to announce the availability of the printed paper version (which should occur in the very next days--the book has already been printed by now) to announce publicly wherever I can (forums, newsletters and so on) the availability of both printed copies and the free PDF. This should happen very soon now, most probably before the end of May 2017.

I hope this answers your questions.

**Comment by zoffixznet** [comment]
It does. Thanks!
