### ISSUE TITLE
weirdness in set difference section

### ISSUE THREAD

**Issue by zengargoyle** [LaurentRosenfeld/thinkperl6#5]
data_struct_selection.tex around line 1016
You introduce ∖ as not \ or (-) and imply that that it can replace a couple of subroutines.
Then you go ahead and use (-) in the code example.

\index{set!difference operator}                                                 
\index{operator!set difference}                                                 
The \verb'∖' (note that this is unicode character \verb'\x2216',               
not the same as the \verb'\' backslash) or \verb'(-)' operator
provides a set difference, so that we needed neither to write a                
{\tt subtract} subroutine nor to construct our own minus operator:              
                                                                                
\begin{verbatim}                                                                
process-line $_ for "emma.txt".IO.lines;-                                       
my $word-list = set "words.txt".IO.lines;                                       
my $unknown-words = %histogram.keys (-) $word-list;                             
say $unknown-words.keys.head(20);                                               
\end{verbatim}

**Comment by LaurentRosenfeld** [comment]
Thank you for your comment, but I do not understand why this would be an issue. The idea is that you can use either **∖** or **(-)** to implement a set difference. So we have two built-in operators to "subtract" a set from another. In the example, I chose to use **(-)**,  which is the so-called "Texas" (pure ASCII) equivalent of  **∖**. Is this not clear? Or do I miss your point?

As a side-note, you appear to be reading the raw LaTeX files. Please note that there is a PDF build of this book freely available on this Web page: http://greenteapress.com/wp/think-perl-6/. It might be easier to read in the PDF format. May be I should include a PDF build on this GitHub repo.

**Comment by LaurentRosenfeld** [comment]
OK, I changed this paragraph to make it hopefully clearer.

I also added a PDF of the book in this GitHub repo.

**Comment by zengargoyle** [comment]
The \verb'∖' (note that this is unicode character \verb'\x2216',
not the same as the \verb'\' backslash) or \verb'(-)' operator
provides a set difference, so that we needed neither to write a
{\tt subtract} subroutine nor to construct our own minus operator:

The \verb'∖' () or \verb'(-)' operator
provides a set difference, so that we needed neither to write a
{\tt subtract} subroutine nor to construct our own minus operator:

ah ..

The \verb'∖' (...) or \verb'(-)' operator

It's the splitting of  \verb'∖' and "or \verb'(-)'" with the long (....) in
the middle
that confused me.

The \verb'∖' (or the texas version \verb'(-)') provides a set difference
... Note that \verb('∖' is the unicode character \verb('\x2216') not the
\verb('\') backslash character.


I would love to see an early introduction of \N{SET MINUS} and unicode
things described as '∖ U+2216 SET MINUS' or similar.

So, you're correct, It's just a little hard to read at first.

On Sun, May 28, 2017 at 1:49 AM, Laurent Rosenfeld <notifications@github.com

**Comment by LaurentRosenfeld** [comment]
I guess it's clearer in the modified version with the note about the unicode character moved into a footnote.

So I'll close the issue if you don't have any objection.

**Comment by zengargoyle** [comment]
No problem.  I forgot to answer a question.... I'm reading the PDF of a few
days ago (when it turned up on IRC #perl6) probably before actual
announcement.  And I'm reading the same PDF since I haven't finished yet :)
),  and looking at the .tex afterwards.  I'll try and make sure that I pull
the latest .tex before complaining.

Again, thanks for the hard work and for the CC license and availability.

On Sun, May 28, 2017 at 8:41 AM, Laurent Rosenfeld <notifications@github.com
