### ISSUE TITLE
I think I found a minor typo

### ISSUE THREAD

**Issue by uzluisf** [LaurentRosenfeld/thinkperl6#8]
In subsection **6.5 Local Variables and Variable Scoping** (pg 89 in the PDF):

> The my keyword **if** often called a declarator, because it is used for declaring a new variable (or other identifier).

Shouldn't it be:
> The my keyword **is** often called a declarator, because it is used for declaring a new variable (or other identifier).

?

**Comment by LaurentRosenfeld** [comment]
Hi Luis,

yes, of course, you are right.

Thank you very much for point this out. I've fixed it on my local Gut repository, and it will appear here soon.

**Comment by uzluisf** [comment]
No problem! 

Thanks to you for such great book!

**Comment by LaurentRosenfeld** [comment]
The typo is now corrected on the Github repo, both in the LaTex source file and in the PDF.

Thank you again.
